export const paths = Object.freeze({
  home: '/',
  programs: '/programs',
  projectDetailsRoute: '/programs/:programId/projects/:projectId',
  getProjectDetails: (programId, projectId) => `/programs/${programId}/projects/${projectId}`,
  auth: Object.freeze({
    login: '/login',
    adminLogin: '/admin/login',
  }),
  donor: Object.freeze({
    campaigns: '/campaigns',
    campaignDetail: '/campaigns/:id',
    projects: '/projects',
    projectDetail: '/projects/:id',
    donate: '/donate',
    donateItem: '/donate/:categoryId/:itemId',
    confirmation: '/confirmation',
    programs: '/programs',
    programDetail: '/programs/:id',
    zakat: '/zakat',
    volunteer: '/volunteer',
    specialRequests: '/special-requests',
    transparency: '/transparency',
    about: '/about',
    contact: '/contact',
    account: '/account',
    blog: '/blog',
    blogDetail: '/blog/:id',
    gallery: '/gallery',
    chat: '/chat',
    updates: '/updates',
    faq: '/faq',
    privacy: '/privacy',
    terms: '/terms',
  }),
  admin: Object.freeze({
    login: '/admin/login',
    dashboard: '/admin',
    programs: '/admin/programs',
    projects: '/admin/projects',
    campaigns: '/admin/campaigns',
    donations: '/admin/donations',
    beneficiaries: '/admin/beneficiaries',
    finance: '/admin/finance',
    reports: '/admin/reports',
    settings: '/admin/settings',
    cms: '/admin/cms',
    blog: '/admin/blog',
    gallery: '/admin/gallery',
    messages: '/admin/messages',
    volunteers: '/admin/volunteers',
    specialRequests: '/admin/special-requests',
  }),
});
